apiVersion: v1
kind: Pod
metadata:
  name: debug-pod
  namespace: dev
spec:
  containers:
  - name: debug
    image: alpine/curl
    command: ["/bin/sh"]
    args: ["-c", "sleep 3600"]
    resources:
      requests:
        cpu: 10m
        memory: 32Mi
      limits:
        cpu: 50m
        memory: 64Mi
  restartPolicy: Never
