apiVersion: v1
kind: Pod
metadata:
  name: test-service
  namespace: dev
spec:
  containers:
  - name: test
    image: alpine/curl
    command: ["/bin/sh"]
    args: ["-c", "curl -v http://genascope-frontend-dev.dev.svc.cluster.local/ && sleep 60"]
    resources:
      requests:
        cpu: 10m
        memory: 32Mi
      limits:
        cpu: 50m
        memory: 64Mi
  restartPolicy: Never
